import { createFileRoute } from "@tanstack/react-router";
import { Search, Star } from "lucide-react";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { menuCategories } from "@/lib/menu-data";
import spreadImage from "@/assets/pizzas-spread.jpg";

const description="Conheça o cardápio completo da Famiglia da Pizza em Belém: pizzas tradicionais, favoritas, gourmet, doces, calzones, massas, entradas, sobremesas e bebidas.";
export const Route=createFileRoute("/cardapio")({head:()=>({meta:[{title:"Nosso Cardápio | Famiglia da Pizza Belém"},{name:"description",content:description},{property:"og:title",content:"Nosso Cardápio | Famiglia da Pizza Belém"},{property:"og:description",content:description},{property:"og:type",content:"website"},{property:"og:url",content:"/cardapio"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/cardapio"}]}),component:MenuPage});

function MenuPage(){
 const [query,setQuery]=useState("");
 const normalized=query.trim().toLocaleLowerCase("pt-BR");
 const groups=useMemo(()=>menuCategories.map(c=>({...c,items:c.items.filter(item=>!normalized||`${item.name} ${item.ingredients}`.toLocaleLowerCase("pt-BR").includes(normalized))})).filter(c=>c.items.length),[normalized]);
 return <><section className="relative mt-20 overflow-hidden bg-ink py-20 text-cream sm:py-28"><img src={spreadImage} alt="Seleção de pizzas artesanais" width={1600} height={1104} className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-ink/65"/><div className="site-container relative"><p className="eyebrow text-gold">Feito artesanalmente</p><h1 className="display-title mt-4">Nosso Cardápio</h1><p className="mt-5 max-w-2xl text-cream/80">Explore todos os sabores da Famiglia. Os preços não estão exibidos porque não foram informados.</p></div></section>
 <div className="sticky top-20 z-30 border-b border-border bg-background/95 py-4 backdrop-blur"><div className="site-container"><div className="relative max-w-md"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por sabor ou ingrediente" aria-label="Buscar no cardápio" className="h-12 bg-card pl-11"/></div><nav className="mt-4 flex gap-2 overflow-x-auto pb-1" aria-label="Categorias do cardápio">{menuCategories.map(c=><a key={c.id} href={`#${c.id}`} className="shrink-0 rounded-full border border-border bg-card px-4 py-2 text-xs font-bold hover:border-primary hover:text-primary">{c.icon} {c.name}</a>)}</nav></div></div>
 <section className="section-pad paper-texture pt-12"><div className="site-container">{groups.length?groups.map(category=><section id={category.id} key={category.id} className="scroll-mt-52 pb-16"><div className="flex items-end gap-4 border-b border-border pb-4"><span className="text-3xl" aria-hidden="true">{category.icon}</span><div><p className="text-xs font-bold uppercase text-primary">{category.items.length} {category.items.length===1?"item":"itens"}</p><h2 className="font-display text-3xl font-semibold sm:text-4xl">{category.name}</h2></div></div><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{category.items.map(item=><article className="menu-card flex min-h-40 flex-col p-6" key={`${category.id}-${item.name}`}><div className="flex items-start justify-between gap-3"><h3 className="font-display text-2xl font-semibold leading-tight">{item.name}</h3>{item.featured&&<span className="flex shrink-0 items-center gap-1 rounded-full bg-gold px-2.5 py-1 text-[10px] font-bold uppercase text-ink"><Star className="size-3 fill-current"/> Destaque</span>}</div><p className="mt-4 text-sm leading-6 text-muted-foreground">{item.ingredients}</p><span className="mt-auto pt-5 text-[10px] font-bold uppercase text-primary">{category.name}</span></article>)}</div></section>):<div className="py-20 text-center"><h2 className="font-display text-3xl">Nenhum item encontrado</h2><p className="mt-2 text-muted-foreground">Tente buscar por outro sabor ou ingrediente.</p></div>}</div></section></>;
}
